# Generated by Django 5.2.4 on 2026-07-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitors.monitor'),
        ),
    ]
